version: '2.2'

services:
  etcd:
    image: "quay.io/coreos/etcd:v3.3"
    container_name: "etcd"
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_API_VERSION: "2"
    ports:
      - 2379:2379
  redis:
    image: "grokzen/redis-cluster:5.0.0"
    container_name: "redis"
    restart: always
    environment:
      STANDALONE: "true"
    ports:
      - '7000-7007:7000-7007'
