PROMETHEUS_METRICS_HTTP_ENDPOINT = "/metrics"

DEFAULT_SUMMARY_QUANTILES = [0.5, 0.75, 0.9, 0.95, 0.99]

DEFAULT_FILE_PATH = "/tmp/metrics"

DEFAULT_CARBON_HOST = "localhost"
DEFAULT_CARBON_PORT = 2003
